grid_map_filters:

  # Duplicate the elevation layer
  - name: first
    type: gridMapFilters/MockFilter
    params:
      processing_time: 100
      print_name: false

  # Normalize the indices
  - name: buffer_normalizer
    type: gridMapFilters/BufferNormalizerFilter
  
  # Fill in gaps using inpainting
  - name: inpaint
    type: gridMapCv/InpaintFilter
    params:
      input_layer: elevation
      output_layer: elevation_inpainted
      radius: 0.10
  
  # Reduce noise using radial blurring
  - name: mean_in_radius
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: elevation_inpainted
      output_layer: elevation_smooth
      radius: 0.10
      
  # Compute surface normals
  - name: surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation_inpainted
      algorithm: raster
      output_layers_prefix: normal_
      normal_vector_positive_axis: z
      parallelization_enabled: true
      thread_number: 4
      
  # Compute slope from surface normal
  - name: slope
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: slope
      expression: acos(normal_z)
      
  # Compute roughness as absolute difference from map to smoothened map
  - name: roughness
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: roughness
      expression: abs(elevation_inpainted - elevation_smooth)
      
  # Compute traversability as normalized weighted sum of slope and roughness
  - name: traversability
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability
      expression: 1.0 - 0.5 * (1.0 - (slope / 0.6)) - 0.5 * (1.0 - (roughness / 0.1))

  # Set lower threshold on traversability
  - name: traversability_lower_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversability
      output_layer: traversability
      lower_threshold: 0.0
      set_to: 0.0

  # Set upper threshold on traversability
  - name: traversability_upper_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversability
      output_layer: traversability
      upper_threshold: 1.0
      set_to: 1.0 # Other uses: .nan, .inf

  # Make binary occupancy grid
  - name: traversable
    type: gridMapFilters/DuplicationFilter
    params:
      input_layer: traversability
      output_layer: traversable
  - name: traversable_lower_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversable
      output_layer: traversable
      lower_threshold: 1.0
      set_to: 0.0
  - name: traversable_upper_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      condition_layer: traversable
      output_layer: traversable
      upper_threshold: 1.0
      set_to: 1.0 # Other uses: .nan, .inf
