#ifndef ETQ_DEFINITIONS_HPP
#define ETQ_DEFINITIONS_HPP

#define DEFAULT_MAX_PLAN_ITERATIONS_GLOBAL 20000
#define DEFAULT_MAX_PLAN_ITERATIONS_LOCAL 5000

#define DEFAULT_MAX_GENERATIONS_GLOBAL 5
#define DEFAULT_MAX_GENERATIONS_LOCAL 5

#define DEFAULT_GOAL_RADIUS 1.0

#define DEFAULT_SAMPLE_TIME 1.0
#define DEFAULT_SAMPLE_DELTA_TIME 0.1

#define DEFAULT_COST_TIME 1.0
#define DEFAULT_COST_DELTA_V 0.25
#define DEFAULT_COST_DELTA_U 0.25

#define DEFAULT_SAMPLE_SIZE 6

#define DEFAULT_VELOCITY_LOOKUP_TABLE {-1.0f, 0.5f, 0.75f, 1.0f, 0.75f, 0.5f}
#define DEFAULT_ROTATION_LOOKUP_TABLE {0.0f, M_PI_4/2.0, M_PI_4/2.0, 0.0f, -M_PI_4/2.0, -M_PI_4/2.0}

#define ETQ_HEIGHT 0.5

#define V_MAX 1.0
#define U_MAX M_PI_4/2.0


#endif